# Numpy: Numerical Python

In [12]:
# Def: numpy is a open source python library used for numerical operations.
# Numpy array are Homogeneous
# Numpy is designed in c, c++ and python

# 1. install, Upgrade and import numpy and  checking its version 

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

# 2. Creating Numpy arrays

In [6]:
# Example-1: numpy array of interger
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)
type(arr1)

[1 2 3 4 5]
int64


numpy.ndarray

In [8]:
# Example-2: numpy array of float
arr2 = np.array([1.1,2.5,3.8,4.2,5.6])
print(arr2)
print(arr2.dtype)
type(arr2)

[1.1 2.5 3.8 4.2 5.6]
float64


numpy.ndarray

In [13]:
# Example-3: numpy array of float + int
arr3 = np.array([1,2.5,3.8,4,5])
print(arr3)
print(arr3.dtype)
type(arr3)

[1.  2.5 3.8 4.  5. ]
float64


numpy.ndarray

In [22]:
# Example-4: numpy array of strings
arr4 = np.array(['shiva','ch@ran','hi'])
print(arr4)
print(arr4.dtype)
type(arr4)

# U : unicode : Special symbols are allowed  in unicode : strings

['shiva' 'ch@ran' 'hi']
<U6


numpy.ndarray

In [25]:
# Example-5: Creating 2D numpy array
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5)
print(type(arr5))
print(arr5.dtype)
print(arr5.ndim) #ndim is used to check the dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2


In [26]:
# Example-6: Creating 3D numpy array
arr6 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
int64
3
