# Numpy: Numerical Python

In [1]:
# Def: numpy is a open source python library used for numerical operations.
# Numpy array are Homogeneous
# Numpy is designed in c, c++ and python

# 1. install, Upgrade and import numpy and  checking its version 

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

# 2. Creating Numpy arrays

In [4]:
# Example-1: numpy array of interger
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)
type(arr1)

[1 2 3 4 5]
int64


numpy.ndarray

In [5]:
# Example-2: numpy array of float
arr2 = np.array([1.1,2.5,3.8,4.2,5.6])
print(arr2)
print(arr2.dtype)
type(arr2)

[1.1 2.5 3.8 4.2 5.6]
float64


numpy.ndarray

In [6]:
# Example-3: numpy array of float + int
arr3 = np.array([1,2.5,3.8,4,5])
print(arr3)
print(arr3.dtype)
type(arr3)

[1.  2.5 3.8 4.  5. ]
float64


numpy.ndarray

In [7]:
# Example-4: numpy array of strings
arr4 = np.array(['shiva','ch@ran','hi'])
print(arr4)
print(arr4.dtype)
type(arr4)

# U : unicode : Special symbols are allowed  in unicode : strings

['shiva' 'ch@ran' 'hi']
<U6


numpy.ndarray

In [8]:
# Example-5: Creating 2D numpy array
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5)
print(type(arr5))
print(arr5.dtype)
print(arr5.ndim) #ndim is used to check the dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2


In [9]:
# Example-6: Creating 3D numpy array
arr6 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
int64
3


In [10]:
arr6.shape

(2, 2, 3)

## 3. Special type numpy arrays

In [17]:
# array of Zeros
arr_zero = np.zeros(5)  #1D
print(arr_zero)

[0. 0. 0. 0. 0.]


In [18]:
arr_zero = np.zeros((2,3))  #2D
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr_zero = np.zeros((3,2,3)) #3D
print(arr_zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
# arr of ones
arr_ones = np.ones(5) #1D
print(arr_ones)

[1. 1. 1. 1. 1.]


In [28]:
arr_ones = np.ones((2,3)) #2D
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
arr_ones = np.ones((2,2,4)) #3D
print(arr_ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [31]:
# initialize the numpy array with specific value
arr_sep = np.full(5,100)
print(arr_sep)

[100 100 100 100 100]


In [34]:
arr_sep = np.full((2,5),100)
print(arr_sep)

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [35]:
arr_sep = np.full((2,2,5),100)
print(arr_sep)

[[[100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]]]


In [37]:
# identity_matrix is a squared matrix: rows = column
# diagonal values are one and all other zero
id_m = np.eye(4)
print(id_m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# randam package to generate random/ synthetic data 

In [39]:
# rand() function generate random elements betwen 0 and 1
np.random.rand(5) #1D

array([0.07340645, 0.68697167, 0.12442155, 0.2346431 , 0.13239026])

In [43]:
np.random.rand(2,5) #2D

array([[0.52910159, 0.33039062, 0.82106805, 0.84538867, 0.72356695],
       [0.58749806, 0.36178226, 0.23378006, 0.34721624, 0.18583412]])

In [44]:
np.random.rand(2,2,5)   #3D

array([[[0.78351717, 0.44618801, 0.05932625, 0.32296457, 0.50617839],
        [0.4415282 , 0.87884417, 0.07955752, 0.37285743, 0.56352936]],

       [[0.68508145, 0.40591217, 0.32887764, 0.73792332, 0.18406782],
        [0.7731828 , 0.81247924, 0.10042608, 0.83621212, 0.2705543 ]]])

In [49]:
#  uniform() function generate uniformaly distributed data
# uniformly distributed means all values have equal probability to get selected 
np.random.uniform(low = 1,high =  10, size =5) #1D

array([3.72606449, 2.16010482, 4.27142986, 8.41810091, 9.29362047])

In [50]:
np.random.uniform(low = 1,high =  10, size =(2,5)) #D

array([[6.86533807, 7.55416872, 4.18196979, 1.34148394, 6.25932305],
       [5.098008  , 1.8086311 , 2.04253292, 9.57035519, 7.9995249 ]])

In [53]:
# random() function just like rand() function
np.random.random((5))

array([0.52537243, 0.05194276, 0.8353546 , 0.26419865, 0.51614342])

In [54]:
np.random.random((2,5))

array([[0.3374356 , 0.59219906, 0.63638052, 0.32950743, 0.95585966],
       [0.14161741, 0.72984696, 0.12239742, 0.92061676, 0.82892405]])

In [61]:
# randn() : strandard normal distribution function. mean = 0,SD=1
# 99.7% values will be b/w -3 to 3
np.random.randn(5)

array([-0.23028007, -0.21464667,  0.94256431,  0.12631358, -0.95541002])

In [62]:
np.random.randn(2,5)

array([[ 1.01395089, -0.55880273, -0.08449274,  0.10577245, -0.33690101],
       [-0.3518875 , -0.70521125, -1.05065352, -0.57622791,  0.11531837]])

In [63]:
np.random.randn(3,2,5)

array([[[-1.04726741, -1.18161855,  0.02305592, -0.53145751,
          1.25371947],
        [-0.51657186, -0.14765403,  0.03585698, -0.44409044,
          1.28832709]],

       [[ 0.57546374,  1.40698309, -1.24621471, -0.21687176,
         -0.96471218],
        [-0.91763687,  0.01756201,  0.82012584, -3.2724714 ,
          0.6713098 ]],

       [[ 0.80657687, -0.80696484, -0.26794685, -2.00622695,
         -0.10741919],
        [-0.83971034, -0.85779157,  1.11641274, -1.45694328,
         -0.19197402]]])

In [67]:
# normal distributed : here mean & SD can be different from 0 and 1
#loc = mean,scale = SD
np.random.normal(loc = 5, scale=1.2, size=10)

array([6.76062918, 3.76842744, 4.25020264, 5.64618667, 6.04945427,
       4.93626536, 3.7323065 , 4.69691441, 5.72183133, 5.12062154])

In [71]:
np.random.normal(loc = 5, scale=1.2, size=(2,5))

array([[5.06446395, 2.95902939, 4.38629127, 2.28012823, 4.05856662],
       [3.2900219 , 5.22558999, 5.27095264, 6.85931653, 6.04236968]])

In [78]:
# choice() function is  used for categorical data
np.random.seed(42)
np.random.choice(['paradise','fauzi','spirit','Puspa','bahubali'],size=3)

array(['Puspa', 'bahubali', 'spirit'], dtype='<U8')

In [80]:
np.random.choice(['paradise','fauzi','spirit','Puspa','bahubali'],p=[0.2,0.05,0.05,0.6,0.1],size=10)

array(['paradise', 'Puspa', 'Puspa', 'paradise', 'Puspa', 'paradise',
       'Puspa', 'bahubali', 'paradise', 'bahubali'], dtype='<U8')

## creating sequences,shuffle,permutation and lineraly seperated data

In [1]:
# arrange() function is used for creating a sequence of elements
# arange() is just similary to range() function
import numpy as np
arr1 = np.arange(10)
print(arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [3]:
arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [6]:
# shuffle() : used for shuffle the elements 
# shuffle() perform inplace operation 
arr1 = np.arange(10)
print(arr1)

np.random.shuffle(arr1)
arr1

[0 1 2 3 4 5 6 7 8 9]


array([2, 1, 3, 9, 4, 7, 5, 6, 0, 8])

In [13]:
# permutation() : shuffle elements but returns new shuffled array
# this don't modify the orginal array
arr1 = np.arange(10)
print(arr1)

arr2 = np.random.permutation(arr1)
print(arr2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[7 6 5 8 4 2 0 1 9 3]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
# linspace(): linearly spaced array
# linspace(start,end,numbermof elements)
arr3 = np.linspace(1,10,10)
print(arr3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [21]:
arr3 = np.linspace(1,10,4)
print(arr3)

[ 1.  4.  7. 10.]


In [30]:
arr3 = np.linspace(1,10,50)
print(arr3)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


# 4. Array Shap,Reshap and transpose

In [38]:
south_f_d = np.array([["shirt "," Lungi", " kurta"],["saree","Anarkali","half saree"]])
print(south_f_d)
print(south_f_d.shape)

[['shirt ' ' Lungi' ' kurta']
 ['saree' 'Anarkali' 'half saree']]
(2, 3)


In [39]:
updated_sfd = south_f_d.reshape(3,2)
print(updated_sfd)

[['shirt ' ' Lungi']
 [' kurta' 'saree']
 ['Anarkali' 'half saree']]


In [40]:
updated_sfd = south_f_d.reshape(1,6)
print(updated_sfd)

[['shirt ' ' Lungi' ' kurta' 'saree' 'Anarkali' 'half saree']]


In [47]:
updated_sfd = south_f_d.reshape(1,2,1,3)
print(updated_sfd)

[[[['shirt ' ' Lungi' ' kurta']]

  [['saree' 'Anarkali' 'half saree']]]]


In [48]:
# while reshaping no.of elements must be same 

In [49]:
# ravel() : used for flatten the array, mens convert any array to 1D array
arr4 = south_f_d.ravel()
print(arr4)

['shirt ' ' Lungi' ' kurta' 'saree' 'Anarkali' 'half saree']


In [52]:
# transopse : rows -> columns & columns->rows
print(south_f_d)
print(south_f_d.T)

[['shirt ' ' Lungi' ' kurta']
 ['saree' 'Anarkali' 'half saree']]
[['shirt ' 'saree']
 [' Lungi' 'Anarkali']
 [' kurta' 'half saree']]


# 5. Size and data type of numpy array

In [53]:
counting_telugu = np.array(['okati','Rendu','moodu','naalugu','Aidu'])
print(counting_telugu.size)

5


In [54]:
print(counting_telugu.dtype)

<U7


In [61]:
# astype():datatype conversion
arr6 = np.array([10.5,20.5,60.5,40.5]).astype(float)
print(arr6)
print(arr6.dtype)

[10.5 20.5 60.5 40.5]
float64


In [63]:
arr6 = np.array(["10","20","60","40"]).astype(float)
print(arr6)
print(arr6.dtype)

[10. 20. 60. 40.]
float64


In [64]:
arr6 = np.array([True,True,True,True]).astype(int)
print(arr6)
print(arr6.dtype)

[1 1 1 1]
int64


# 6. indexing & slicing % modification

In [1]:
import numpy as np
s_s = np.array([["motichoor","kalakand","jalabi"],["poli","gariyalu","khaja"]])
print(s_s[0][0])

motichoor


In [2]:
print(s_s[1,1:3]) #[row,range]

['gariyalu' 'khaja']


In [3]:
print(s_s[0,1:3])

['kalakand' 'jalabi']


In [4]:
print(s_s[0,:2])

['motichoor' 'kalakand']


In [5]:
s_s = np.array([["motichoor","kalakand","jalabi"],["poli","gariyalu","khaja"]])
print(s_s[:,:2])

[['motichoor' 'kalakand']
 ['poli' 'gariyalu']]


In [6]:
print(s_s[-1,-2])

gariyalu


In [7]:
print(s_s[-1:,-1:-2:-1])

[['khaja']]


In [9]:
# Modification, insertion and deletion in numpy
import numpy as np
s_s = np.array([["motichoor","kalakand","jalabi"],["poli","gariyalu","khaja"]])
# Modification
s_s[0,0] = 'payasum'
print(s_s)

[['payasum' 'kalakand' 'jalabi']
 ['poli' 'gariyalu' 'khaja']]


In [10]:
# updated complete row
s_s[1] = ['kesari','pulareddy','arasalu']
print(s_s)

[['payasum' 'kalakand' 'jalabi']
 ['kesari' 'pulareddy' 'arasalu']]


In [11]:
# updated complete column
# numpy array take fix space to store data
s_s[:,2] = ['mysurepak','doublekamitha']
print(s_s)

[['payasum' 'kalakand' 'mysurepak']
 ['kesari' 'pulareddy' 'doublekam']]


In [20]:
# Insert operation : new row
s_s = np.insert(s_s,1,['gajarpak','rusmali','firni'], axis = 0)
print(s_s)

[['payasum' 'kalakand' 'mysurepak']
 ['gajarpak' 'rusmali' 'firni']
 ['kesari' 'pulareddy' 'doublekam']]


In [21]:
# insert operation : new column  
s_s = np.insert(s_s,2,['radbhari','gulabjamun','kheer'], axis = 1)
print(s_s)

[['payasum' 'kalakand' 'radbhari' 'mysurepak']
 ['gajarpak' 'rusmali' 'gulabjamu' 'firni']
 ['kesari' 'pulareddy' 'kheer' 'doublekam']]


In [22]:
# insert operation : multiple columns
s_s = np.insert(s_s,2,[['kajukatli','ghevar','peda'],['kajukatli','ghevar','peda']], axis = 1)
print(s_s)

[['payasum' 'kalakand' 'kajukatli' 'kajukatli' 'radbhari' 'mysurepak']
 ['gajarpak' 'rusmali' 'ghevar' 'ghevar' 'gulabjamu' 'firni']
 ['kesari' 'pulareddy' 'peda' 'peda' 'kheer' 'doublekam']]


In [23]:
# delete operation 
s_s=np.delete(s_s,0, axis=0)
print(s_s)

[['gajarpak' 'rusmali' 'ghevar' 'ghevar' 'gulabjamu' 'firni']
 ['kesari' 'pulareddy' 'peda' 'peda' 'kheer' 'doublekam']]


In [24]:
s_s=np.delete(s_s,2, axis=1)
print(s_s)

[['gajarpak' 'rusmali' 'ghevar' 'gulabjamu' 'firni']
 ['kesari' 'pulareddy' 'peda' 'kheer' 'doublekam']]


In [26]:
s_s=np.delete(s_s,[1,3], axis=1)
print(s_s)

[['gajarpak' 'ghevar' 'firni']
 ['kesari' 'peda' 'doublekam']]


# 7. Mathematical & statistical operations

In [28]:
sweet_price = np.array([[450,600,400],[850,400,250]])
print(sweet_price+100)

[[550 700 500]
 [950 500 350]]


In [29]:
print(sweet_price*2)

[[ 900 1200  800]
 [1700  800  500]]


In [30]:
np.sum(sweet_price)

np.int64(2950)

In [31]:
print(np.min(sweet_price))

250


In [32]:
print(np.max(sweet_price))

850


In [33]:
print(np.mean(sweet_price))

491.6666666666667


In [34]:
print(np.var(sweet_price))

36180.555555555555


In [36]:
# strandard deviation: how much the data for away from the mean 
print(np.std(sweet_price))

190.21187017522212


In [46]:
# 50% of the people are below 425
print(np.percentile(sweet_price,50))

425.0


In [47]:
# quantile is special type of percentile
np.quantile(sweet_price,0.50)

np.float64(425.0)

In [49]:
# return the index of largest value
age = [22,16,500,14,8,20,90,200]
np.argmax(age)

np.int64(2)

In [50]:
# return the index of smallest value
age = [22,16,500,14,8,20,90,200]
np.argmin(age)

np.int64(4)

In [51]:
pi = 3.142367459245
np.round(pi,3)

np.float64(3.142)

In [52]:
np.sqrt(900)

np.float64(30.0)

In [53]:
np.floor(pi)

np.float64(3.0)

In [55]:
np.ceil(pi)

np.float64(4.0)

In [56]:
np.abs(-19)

np.int64(19)