# Numpy: Numerical Python

In [1]:
# Def: numpy is a open source python library used for numerical operations.
# Numpy array are Homogeneous
# Numpy is designed in c, c++ and python

# 1. install, Upgrade and import numpy and  checking its version 

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

# 2. Creating Numpy arrays

In [4]:
# Example-1: numpy array of interger
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)
type(arr1)

[1 2 3 4 5]
int64


numpy.ndarray

In [5]:
# Example-2: numpy array of float
arr2 = np.array([1.1,2.5,3.8,4.2,5.6])
print(arr2)
print(arr2.dtype)
type(arr2)

[1.1 2.5 3.8 4.2 5.6]
float64


numpy.ndarray

In [6]:
# Example-3: numpy array of float + int
arr3 = np.array([1,2.5,3.8,4,5])
print(arr3)
print(arr3.dtype)
type(arr3)

[1.  2.5 3.8 4.  5. ]
float64


numpy.ndarray

In [7]:
# Example-4: numpy array of strings
arr4 = np.array(['shiva','ch@ran','hi'])
print(arr4)
print(arr4.dtype)
type(arr4)

# U : unicode : Special symbols are allowed  in unicode : strings

['shiva' 'ch@ran' 'hi']
<U6


numpy.ndarray

In [8]:
# Example-5: Creating 2D numpy array
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5)
print(type(arr5))
print(arr5.dtype)
print(arr5.ndim) #ndim is used to check the dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2


In [9]:
# Example-6: Creating 3D numpy array
arr6 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
int64
3


In [10]:
arr6.shape

(2, 2, 3)

## 3. Special type numpy arrays

In [17]:
# array of Zeros
arr_zero = np.zeros(5)  #1D
print(arr_zero)

[0. 0. 0. 0. 0.]


In [18]:
arr_zero = np.zeros((2,3))  #2D
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr_zero = np.zeros((3,2,3)) #3D
print(arr_zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
# arr of ones
arr_ones = np.ones(5) #1D
print(arr_ones)

[1. 1. 1. 1. 1.]


In [28]:
arr_ones = np.ones((2,3)) #2D
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
arr_ones = np.ones((2,2,4)) #3D
print(arr_ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [31]:
# initialize the numpy array with specific value
arr_sep = np.full(5,100)
print(arr_sep)

[100 100 100 100 100]


In [34]:
arr_sep = np.full((2,5),100)
print(arr_sep)

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [35]:
arr_sep = np.full((2,2,5),100)
print(arr_sep)

[[[100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]]]


In [37]:
# identity_matrix is a squared matrix: rows = column
# diagonal values are one and all other zero
id_m = np.eye(4)
print(id_m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# randam package to generate random/ synthetic data 

In [39]:
# rand() function generate random elements betwen 0 and 1
np.random.rand(5) #1D

array([0.07340645, 0.68697167, 0.12442155, 0.2346431 , 0.13239026])

In [43]:
np.random.rand(2,5) #2D

array([[0.52910159, 0.33039062, 0.82106805, 0.84538867, 0.72356695],
       [0.58749806, 0.36178226, 0.23378006, 0.34721624, 0.18583412]])

In [44]:
np.random.rand(2,2,5)   #3D

array([[[0.78351717, 0.44618801, 0.05932625, 0.32296457, 0.50617839],
        [0.4415282 , 0.87884417, 0.07955752, 0.37285743, 0.56352936]],

       [[0.68508145, 0.40591217, 0.32887764, 0.73792332, 0.18406782],
        [0.7731828 , 0.81247924, 0.10042608, 0.83621212, 0.2705543 ]]])

In [49]:
#  uniform() function generate uniformaly distributed data
# uniformly distributed means all values have equal probability to get selected 
np.random.uniform(low = 1,high =  10, size =5) #1D

array([3.72606449, 2.16010482, 4.27142986, 8.41810091, 9.29362047])

In [50]:
np.random.uniform(low = 1,high =  10, size =(2,5)) #D

array([[6.86533807, 7.55416872, 4.18196979, 1.34148394, 6.25932305],
       [5.098008  , 1.8086311 , 2.04253292, 9.57035519, 7.9995249 ]])

In [53]:
# random() function just like rand() function
np.random.random((5))

array([0.52537243, 0.05194276, 0.8353546 , 0.26419865, 0.51614342])

In [54]:
np.random.random((2,5))

array([[0.3374356 , 0.59219906, 0.63638052, 0.32950743, 0.95585966],
       [0.14161741, 0.72984696, 0.12239742, 0.92061676, 0.82892405]])

In [61]:
# randn() : strandard normal distribution function. mean = 0,SD=1
# 99.7% values will be b/w -3 to 3
np.random.randn(5)

array([-0.23028007, -0.21464667,  0.94256431,  0.12631358, -0.95541002])

In [62]:
np.random.randn(2,5)

array([[ 1.01395089, -0.55880273, -0.08449274,  0.10577245, -0.33690101],
       [-0.3518875 , -0.70521125, -1.05065352, -0.57622791,  0.11531837]])

In [63]:
np.random.randn(3,2,5)

array([[[-1.04726741, -1.18161855,  0.02305592, -0.53145751,
          1.25371947],
        [-0.51657186, -0.14765403,  0.03585698, -0.44409044,
          1.28832709]],

       [[ 0.57546374,  1.40698309, -1.24621471, -0.21687176,
         -0.96471218],
        [-0.91763687,  0.01756201,  0.82012584, -3.2724714 ,
          0.6713098 ]],

       [[ 0.80657687, -0.80696484, -0.26794685, -2.00622695,
         -0.10741919],
        [-0.83971034, -0.85779157,  1.11641274, -1.45694328,
         -0.19197402]]])

In [67]:
# normal distributed : here mean & SD can be different from 0 and 1
#loc = mean,scale = SD
np.random.normal(loc = 5, scale=1.2, size=10)

array([6.76062918, 3.76842744, 4.25020264, 5.64618667, 6.04945427,
       4.93626536, 3.7323065 , 4.69691441, 5.72183133, 5.12062154])

In [71]:
np.random.normal(loc = 5, scale=1.2, size=(2,5))

array([[5.06446395, 2.95902939, 4.38629127, 2.28012823, 4.05856662],
       [3.2900219 , 5.22558999, 5.27095264, 6.85931653, 6.04236968]])

In [78]:
# choice() function is  used for categorical data
np.random.seed(42)
np.random.choice(['paradise','fauzi','spirit','Puspa','bahubali'],size=3)

array(['Puspa', 'bahubali', 'spirit'], dtype='<U8')

In [80]:
np.random.choice(['paradise','fauzi','spirit','Puspa','bahubali'],p=[0.2,0.05,0.05,0.6,0.1],size=10)

array(['paradise', 'Puspa', 'Puspa', 'paradise', 'Puspa', 'paradise',
       'Puspa', 'bahubali', 'paradise', 'bahubali'], dtype='<U8')

# 4. Array Shap,Reshap and transpose